name: Deploy
description: Deploys service to k8s cluster

inputs:
  VERSION:
    description: "For example, '1.2.34' or 'staging-abc3133'"
    required: true

runs:
  using: composite
  steps:
    - name: Deploy service
      shell: bash
      run: bun run .github/scripts/src/deploy --newTagVersion "${{ inputs.VERSION }}"
