name: Promote Docker image to tag
description: Finds a Docker image by the given tag and promotes it to the new tag (does not replace).

inputs:
  ORIGINAL_TAG:
    description: "For example: staging-abc1234"
    required: true
  NEW_GITHUB_TAG:
    description: "For example: 1.2.34"
    required: true

runs:
  using: composite
  steps:
    - name: Promote tag
      shell: bash
      run: bun run .github/scripts/src/promote --originalTag "${{ inputs.ORIGINAL_TAG }}" --newGithubTag "${{ inputs.NEW_GITHUB_TAG }}"
