# yaml-language-server: $schema=https://raw.githubusercontent.com/SchemaStore/schemastore/refs/heads/master/src/schemas/json/github-workflow.json
name: CI-CD
run-name: Running CICD on ${{ github.actor }}'s commits

on:
  push:
    branches:
      - main
  pull_request:

concurrency:
  group: ci-cd-${{ github.ref }}
  cancel-in-progress: true

jobs:
  test:
    name: Run Tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup CI
        uses: ./.github/composite/setup-ci

      - name: Setup pnpm
        uses: pnpm/action-setup@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20"
          cache: "pnpm"

      - name: Install Dependencies
        run: pnpm install -r --frozen-lockfile

      - name: Run Tests
        run: pnpm run test

  buildTestImage:
    name: Build Test Docker Image
    needs: test
    runs-on: ubuntu-latest

    if: github.ref_name != 'main'

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup CI
        uses: ./.github/composite/setup-ci
        with:
          GPG_PRIVATE_KEY: ${{ secrets.GPG_PRIVATE_KEY }}
          GPG_PASSPHRASE: ${{ secrets.GPG_PASSPHRASE }}

      - name: Upload image
        uses: ./.github/composite/upload-image
        with:
          DOCKER_UPLOAD: "false"

  buildImage:
    name: Build Docker Image
    needs: test
    runs-on: ubuntu-latest

    if: github.ref_name == 'main'

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup CI
        uses: ./.github/composite/setup-ci
        with:
          GPG_PRIVATE_KEY: ${{ secrets.GPG_PRIVATE_KEY }}
          GPG_PASSPHRASE: ${{ secrets.GPG_PASSPHRASE }}

      - name: Upload image
        uses: ./.github/composite/upload-image
